# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: PPC1
    url: $PPC1
  - name: PPC2
    url: $PPC2
  - name: WebDoc
    url: $BTP
  - name: Site Groupe
    url: https://groupechaumeil.fr/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.groupechaumeil.fr
  # baseUrl: /your-repo-name
  logoUrl: https://groupechaumeil.fr/wp-content/uploads/2020/02/Groupe-Chaumeil-logo.png
  name: Status sites groupe Chaumeil
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
